### ISSUE TITLE
Multiple graphsets

### ISSUE THREAD

**Issue by gitbnw** [PINT/ZingChart-jQuery#1]
Is there a way to single out "graphsets" within a graph object i.e. if i have two charts loaded?  Cool project btw :)

**Comment by patrickrodee** [comment]
Hey there! As of now, there's no built-in graphset targeting but we plan to add it in the next release (going live in the next few weeks).

Also, we'll eventually be closing this repo down as we've moved it [to a new location](https://github.com/zingchart/ZingChart-jQuery). Let us know if you have any other questions!
